### ISSUE TITLE
Fails to build on Ruby 3.3.0 (use of undeclared identifier 'RSTRING_EMBED_LEN_MAX')

### ISSUE THREAD

**Issue by 2called-chaos** [wincent/wikitext#14]
```
parser.c:2593:32: error: use of undeclared identifier 'RSTRING_EMBED_LEN_MAX'; did you mean 'RVALUE_EMBED_LEN_MAX'?
    VALUE out = rb_str_buf_new(RSTRING_EMBED_LEN_MAX + 1);
                               ^~~~~~~~~~~~~~~~~~~~~
                               RVALUE_EMBED_LEN_MAX
```

~~Removed in https://github.com/ruby/ruby/pull/7908/commits/24fdbd2c9cdb60a75d711131872f7c096b2ba60d (or https://github.com/ruby/ruby/pull/7908, github removes the pull reference when parsing links)~~

Removed in https://github.com/ruby/ruby/commit/1da2e7fca35dc697d85dd91d2572ab58d08cd3bc / https://github.com/ruby/ruby/pull/7655

---

I'm not proficient with C but from what I understand we can just use `RSTRING_LEN` instead?

**Comment by namiwang** [comment]
FYI with latest ruby 3.4.7 I've encountered another error

```
wikitext.c:116:13: error: incompatible function pointer types passing 'VALUE (VALUE, VALUE)' (aka 'unsigned long (unsigned long, unsigned long)') to parameter of type 'rb_block_call_func_t' (aka 'unsigned long (*)(unsigned long, unsigned long, int,
const unsigned long *, unsigned long)') [-Wincompatible-function-pointer-types]
  116 |             wikitext_on_load_block, Qnil);
      |             ^~~~~~~~~~~~~~~~~~~~~~
/Users/nami/.asdf/installs/ruby/3.4.7/include/ruby-3.4.0/ruby/internal/iterator.h:283:75: note: passing argument to parameter 'proc' here
  283 | VALUE rb_iterate(VALUE (*func1)(VALUE), VALUE data1, rb_block_call_func_t proc, VALUE data2);
      |                                                                           ^
1 warning and 1 error generated.
```

**Comment by wincent** [comment]
Should be fixed by:

- https://github.com/wincent/wikitext/commit/4427e4c0b705e6eec5b7a93c92ebed1d1b86cb4f
- https://github.com/wincent/wikitext/commit/13ab94bb16400cabd33c5fdf6db72526ba8f6233
